"""
Django settings for otterball_v2 project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os.path
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# `or` rather than a getenv default, here and below: compose passes every
# variable in its environment block through, so one that is merely *declared*
# in .env (`CELERY_RESULT_BACKEND=`) arrives as an empty string and would beat
# the default a `getenv(..., fallback)` provides.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY") or "django-insecure-*!wb43v++a(-#-=_i3cj%e%mm!ycwi^t2ls#4f*3%m3i40i#!7"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("ENV") != "production"

ALLOWED_HOSTS = (os.getenv("ALLOWED_HOSTS") or "*").split(",")

# Where the read-only public pages are reachable from the outside. The bot
# links players to their season's fixtures, leaderboard and stats, and it has
# no request to build an absolute URL from - a Discord message is not served
# by Django. Trailing slash stripped so a path can always be appended.
PUBLIC_SITE_URL = (os.getenv("PUBLIC_SITE_URL") or "https://otterball.byilli.com").rstrip("/")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users.apps.UsersConfig",
    "sports.apps.SportsConfig",
    "predictions.apps.PredictionsConfig",
    "discord_bot.apps.DiscordBotConfig",
    "django_celery_results",
    "django_celery_beat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise, extended to serve MEDIA_ROOT as well - there is no proxy in
    # front of gunicorn to do it.
    "otterball_v2.middleware.WhiteNoiseWithMediaMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "otterball_v2.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "otterball_v2.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    parsed_db = urlparse(DATABASE_URL)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": parsed_db.path.lstrip("/"),
            "USER": parsed_db.username,
            "PASSWORD": parsed_db.password,
            "HOST": parsed_db.hostname,
            "PORT": parsed_db.port or 5432,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "users.User"

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TZ") or "Europe/Berlin"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# WhiteNoise builds its file index once, at startup. That is fine for
# STATIC_ROOT, which collectstatic fills before gunicorn boots, but crests land
# in MEDIA_ROOT whenever ingestion meets a team it has not seen - written by the
# worker container into the volume the web container is already serving from.
# Without this, a crest downloaded after boot 404s until `web` restarts.
# The cost is a couple of stat() calls per request instead of a dict lookup.
WHITENOISE_AUTOREFRESH = True

REDIS_URL = os.getenv("REDIS_URL") or "redis://127.0.0.1:6379/1"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL") or REDIS_URL
# An empty backend means no TaskResult rows, and readiness reads the newest one
# to notice that a scheduled task is *failing* rather than merely not running.
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND") or "django-db"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "rich.logging.RichHandler",
            "rich_tracebacks": True,
            "tracebacks_show_locals": True,
        }
    },
    "loggers": {
        "": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}

REDIS_MATCH_UPDATE_TOPIC = "match_update"

# A starting Celery worker runs the overdue infrastructure syncs once, so a
# spell with Beat down does not leave a pool stranded without fixtures. It
# never writes PeriodicTask.last_run_at, so check_pool keeps reporting the
# schedule as stale and a dead Beat stays visible. Set to 0 to leave the
# schedule entirely to Beat.
INGESTION_CATCHUP_ENABLED = os.getenv("INGESTION_CATCHUP_ENABLED", "1") not in ("0", "false", "False")
