# Generated by Django 6.0.6 on 2026-06-24 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("SOCCER", "Soccer"),
                            ("AMERICAN_FOOTBALL", "American Football"),
                        ],
                        default="SOCCER",
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        default="MALE",
                        max_length=10,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="sports.competition",
                    ),
                ),
            ],
            options={
                "unique_together": {("competition", "year")},
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("GROUP", "Group Stage"),
                            ("R32", "Round of 32"),
                            ("R16", "Round of 16"),
                            ("QF", "Quarter-Finals"),
                            ("SF", "Semi-Finals"),
                            ("TPP", "Third Place Playoff"),
                            ("FINAL", "Final"),
                        ],
                        default="GROUP",
                        max_length=10,
                    ),
                ),
                ("level", models.IntegerField(default=0)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="sports.season",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("SOCCER", "Soccer"),
                            ("AMERICAN_FOOTBALL", "American Football"),
                        ],
                        default="SOCCER",
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        default="MALE",
                        max_length=10,
                    ),
                ),
                ("logo_url", models.URLField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="team_logos"),
                ),
                ("color", models.CharField(default="#60669c", max_length=9)),
            ],
            options={
                "indexes": [models.Index(fields=["name", "sport"], name="sports_team_name_2572d1_idx")],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kickoff", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("LIVE", "Live"),
                            ("FINISHED", "Finished"),
                            ("POSTPONED", "Postponed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=15,
                    ),
                ),
                ("home_score", models.IntegerField(blank=True, null=True)),
                ("away_score", models.IntegerField(blank=True, null=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="sports.stage",
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="sports.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Matches",
            },
        ),
        migrations.CreateModel(
            name="TeamMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("FIFA", "FIFA Official API"),
                            ("ESPN", "ESPN Sports Data"),
                        ],
                        default="FIFA",
                        max_length=50,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="sports.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompetitionMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("FIFA", "FIFA Official API"),
                            ("ESPN", "ESPN Sports Data"),
                        ],
                        default="FIFA",
                        max_length=50,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="sports.competition",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="MatchMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("FIFA", "FIFA Official API"),
                            ("ESPN", "ESPN Sports Data"),
                        ],
                        default="FIFA",
                        max_length=50,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="sports.match",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="SeasonMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("FIFA", "FIFA Official API"),
                            ("ESPN", "ESPN Sports Data"),
                        ],
                        default="FIFA",
                        max_length=50,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="sports.season",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="StageMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("FIFA", "FIFA Official API"),
                            ("ESPN", "ESPN Sports Data"),
                        ],
                        default="FIFA",
                        max_length=50,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="sports.stage",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "external_id")},
            },
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["status", "kickoff"], name="sports_matc_status_09ed92_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="teammapping",
            unique_together={("provider", "external_id")},
        ),
    ]
