# Generated by Django 6.0.6 on 2026-06-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="stage_type",
            field=models.CharField(
                choices=[
                    ("GROUP", "Group Stage"),
                    ("KNOCK_OUT", "Knockout Stage"),
                    ("LEAGUE", "League"),
                    ("OTHER", "Other"),
                ],
                default="GROUP",
                max_length=10,
            ),
        ),
    ]
