# Generated by Django 6.0.7 on 2026-08-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0002_alter_stage_stage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionmapping",
            name="provider",
            field=models.CharField(
                choices=[
                    ("FIFA", "FIFA Official API"),
                    ("ESPN", "ESPN Sports Data"),
                    ("NFLVERSE", "nflverse Schedule Data"),
                ],
                default="FIFA",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="matchmapping",
            name="provider",
            field=models.CharField(
                choices=[
                    ("FIFA", "FIFA Official API"),
                    ("ESPN", "ESPN Sports Data"),
                    ("NFLVERSE", "nflverse Schedule Data"),
                ],
                default="FIFA",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="seasonmapping",
            name="provider",
            field=models.CharField(
                choices=[
                    ("FIFA", "FIFA Official API"),
                    ("ESPN", "ESPN Sports Data"),
                    ("NFLVERSE", "nflverse Schedule Data"),
                ],
                default="FIFA",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="stagemapping",
            name="provider",
            field=models.CharField(
                choices=[
                    ("FIFA", "FIFA Official API"),
                    ("ESPN", "ESPN Sports Data"),
                    ("NFLVERSE", "nflverse Schedule Data"),
                ],
                default="FIFA",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="teammapping",
            name="provider",
            field=models.CharField(
                choices=[
                    ("FIFA", "FIFA Official API"),
                    ("ESPN", "ESPN Sports Data"),
                    ("NFLVERSE", "nflverse Schedule Data"),
                ],
                default="FIFA",
                max_length=50,
            ),
        ),
    ]
