import datetime
from pathlib import Path

from django.conf import settings
from django.core.management import call_command
from django.core.management.base import BaseCommand

# Excluded because they're either regenerated by Django on migrate (contenttypes,
# auth.permission), pure server-side ephemera (sessions), or noisy task-run history
# with no restore value (django_celery_results). Everything else - including the
# actual sports/predictions/discord_bot data and django_celery_beat schedules - is kept.
DEFAULT_EXCLUDED_APPS = [
    "contenttypes",
    "sessions",
    "admin",
    "auth.permission",
    "django_celery_results",
]


class Command(BaseCommand):
    help = (
        "Exports the full database to a single compressed JSON fixture, suitable for restoring "
        "with import_db. Uses natural keys so user references survive a restore into an empty "
        "database, and skips derived/ephemeral tables by default."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "output",
            nargs="?",
            help="Output file path (default: backups/otterball_<timestamp>.json.gz). "
            "Extension controls compression (.json, .json.gz, .json.bz2, .json.zip).",
        )
        parser.add_argument(
            "--exclude",
            action="append",
            default=[],
            metavar="APP_LABEL[.ModelName]",
            help="Additional app or model to exclude, on top of the defaults. Can be repeated.",
        )

    def handle(self, *args, **options):
        output = options["output"]
        if not output:
            backups_dir = Path(settings.BASE_DIR) / "backups"
            backups_dir.mkdir(exist_ok=True)
            timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            output = str(backups_dir / f"otterball_{timestamp}.json.gz")

        call_command(
            "dumpdata",
            natural_foreign=True,
            natural_primary=True,
            exclude=DEFAULT_EXCLUDED_APPS + options["exclude"],
            output=output,
        )

        size_kib = Path(output).stat().st_size / 1024
        self.stdout.write(self.style.SUCCESS(f"Exported database to {output} ({size_kib:.1f} KiB)"))
