import datetime
import tarfile
import tempfile
from pathlib import Path

from django.conf import settings
from django.core.management import call_command
from django.core.management.base import BaseCommand, CommandError

# Excluded because they're either regenerated by Django on migrate (contenttypes,
# auth.permission), pure server-side ephemera (sessions), or noisy task-run history
# with no restore value (django_celery_results). Everything else - including the
# actual sports/predictions/discord_bot data and django_celery_beat schedules - is kept.
DEFAULT_EXCLUDED_APPS = [
    "contenttypes",
    "sessions",
    "admin",
    "auth.permission",
    "django_celery_results",
]

# Layout inside a bundle. import_db looks for exactly these names, so they are a
# format contract between the two commands rather than an implementation detail.
BUNDLE_FIXTURE_NAME = "data.json"
BUNDLE_MEDIA_DIR = "media"

TAR_SUFFIXES = (".tar.gz", ".tgz", ".tar")
GZIPPED_TAR_SUFFIXES = (".tar.gz", ".tgz")


def is_bundle_path(path: Path) -> bool:
    """A bundle carries the fixture *and* the media tree, so it has to be a tarball."""
    return str(path).endswith(TAR_SUFFIXES)


class Command(BaseCommand):
    help = (
        "Exports the full database, plus the media tree, to a single compressed bundle suitable "
        "for restoring with import_db. Uses natural keys so user references survive a restore "
        "into an empty database, and skips derived/ephemeral tables by default."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "output",
            nargs="?",
            help="Output file path (default: backups/otterball_<timestamp>.tar.gz). "
            "A .tar.gz/.tgz/.tar name produces a bundle of the database and the media files; "
            "a .json/.json.gz/.json.bz2/.json.zip name produces a database-only fixture.",
        )
        parser.add_argument(
            "--exclude",
            action="append",
            default=[],
            metavar="APP_LABEL[.ModelName]",
            help="Additional app or model to exclude, on top of the defaults. Can be repeated.",
        )
        parser.add_argument(
            "--no-media",
            action="store_true",
            help="Export the database only, leaving the media files (team logos) out",
        )

    def handle(self, *args, **options):
        include_media = not options["no_media"]

        output = options["output"]
        if not output:
            backups_dir = Path(settings.BASE_DIR) / "backups"
            backups_dir.mkdir(exist_ok=True)
            timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            suffix = ".tar.gz" if include_media else ".json.gz"
            output = str(backups_dir / f"otterball_{timestamp}{suffix}")

        output_path = Path(output)
        if include_media and not is_bundle_path(output_path):
            raise CommandError(
                f"{output_path.name} is a plain fixture, which cannot carry the media files. "
                f"Give it a .tar.gz name for a full bundle, or pass --no-media."
            )
        output_path.parent.mkdir(parents=True, exist_ok=True)

        if not is_bundle_path(output_path):
            self._dump_fixture(str(output_path), options["exclude"])
            self.stdout.write(
                self.style.SUCCESS(f"Exported database to {output_path} ({self._size(output_path)}, no media)")
            )
            return

        media_files = self._media_files() if include_media else []
        if include_media and not media_files:
            self.stdout.write(
                self.style.WARNING(f"No media files found under {settings.MEDIA_ROOT} - bundling anyway")
            )

        with tempfile.TemporaryDirectory() as tmpdir:
            fixture_path = Path(tmpdir) / BUNDLE_FIXTURE_NAME
            self._dump_fixture(str(fixture_path), options["exclude"])

            mode = "w:gz" if str(output_path).endswith(GZIPPED_TAR_SUFFIXES) else "w"
            media_root = Path(settings.MEDIA_ROOT)
            with tarfile.open(output_path, mode) as tar:
                tar.add(fixture_path, arcname=BUNDLE_FIXTURE_NAME)
                for media_file in media_files:
                    arcname = Path(BUNDLE_MEDIA_DIR) / media_file.relative_to(media_root)
                    tar.add(media_file, arcname=str(arcname))

        self.stdout.write(
            self.style.SUCCESS(
                f"Exported database + {len(media_files)} media file(s) to "
                f"{output_path} ({self._size(output_path)})"
            )
        )

    def _dump_fixture(self, output, extra_excludes):
        call_command(
            "dumpdata",
            natural_foreign=True,
            natural_primary=True,
            exclude=DEFAULT_EXCLUDED_APPS + extra_excludes,
            output=output,
        )

    @staticmethod
    def _media_files() -> list[Path]:
        media_root = Path(settings.MEDIA_ROOT)
        if not media_root.is_dir():
            return []
        return sorted(path for path in media_root.rglob("*") if path.is_file())

    @staticmethod
    def _size(path: Path) -> str:
        size_kib = path.stat().st_size / 1024
        if size_kib < 1024:
            return f"{size_kib:.1f} KiB"
        return f"{size_kib / 1024:.1f} MiB"
