# Generated by Django 6.0.6 on 2026-06-24 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordChannel",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("position", models.IntegerField(default=0)),
                ("channel_type", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["guild_id", "position"],
            },
        ),
        migrations.CreateModel(
            name="DiscordGuild",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiscordGuildPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leaderboard_msg",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiscordGuildRole",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("position", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiscordProfile",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                (
                    "global_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("wants_notifications", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiscordTeamEmoji",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ActiveMatchMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_id", models.BigIntegerField()),
                ("poll_message_id", models.BigIntegerField(unique=True)),
                ("is_poll_finalized", models.BooleanField(default=False)),
                (
                    "ticker_message_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("is_ticker_finalized", models.BooleanField(default=False)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_messages",
                        to="sports.match",
                    ),
                ),
            ],
        ),
    ]
