# Generated by Django 6.0.6 on 2026-06-24 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discord_bot", "0001_initial"),
        ("predictions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activematchmessage",
            name="pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_messages",
                to="predictions.predictionpool",
            ),
        ),
        migrations.AddField(
            model_name="activematchmessage",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_messages",
                to="discord_bot.discordchannel",
            ),
        ),
        migrations.AddField(
            model_name="discordchannel",
            name="guild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="discord_bot.discordguild",
            ),
        ),
        migrations.AddField(
            model_name="activematchmessage",
            name="guild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_messages",
                to="discord_bot.discordguild",
            ),
        ),
        migrations.AddField(
            model_name="discordguildpool",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_pools",
                to="discord_bot.discordchannel",
            ),
        ),
        migrations.AddField(
            model_name="discordguildpool",
            name="guild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pool_configurations",
                to="discord_bot.discordguild",
            ),
        ),
        migrations.AddField(
            model_name="discordguildpool",
            name="pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guild_configurations",
                to="predictions.predictionpool",
            ),
        ),
        migrations.AddField(
            model_name="discordguild",
            name="active_pools",
            field=models.ManyToManyField(
                blank=True,
                related_name="active_in_guilds",
                through="discord_bot.DiscordGuildPool",
                to="predictions.predictionpool",
            ),
        ),
        migrations.AddField(
            model_name="discordguildrole",
            name="guild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="discord_bot.discordguild",
            ),
        ),
        migrations.AddField(
            model_name="discordguildpool",
            name="notification_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_roles",
                to="discord_bot.discordguildrole",
            ),
        ),
    ]
