# Generated by Django 6.0.6 on 2026-06-24 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discord_bot", "0002_initial"),
        ("sports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discordprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discord_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discordteamemoji",
            name="team",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emoji",
                to="sports.team",
            ),
        ),
        migrations.AddIndex(
            model_name="activematchmessage",
            index=models.Index(fields=["poll_message_id"], name="discord_bot_poll_me_9857d7_idx"),
        ),
        migrations.AddIndex(
            model_name="activematchmessage",
            index=models.Index(fields=["ticker_message_id"], name="discord_bot_ticker__b892fd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="activematchmessage",
            unique_together={("match", "guild", "pool")},
        ),
        migrations.AlterUniqueTogether(
            name="discordguildpool",
            unique_together={("guild", "pool")},
        ),
    ]
