# Generated by Django 6.0.6 on 2026-06-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_bot", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activematchmessage",
            name="poll_use_fallback_answer_ordering",
            field=models.BooleanField(default=False),
        ),
    ]
