# Generated by Django 6.0.8 on 2026-08-25 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_bot", "0004_activematchmessage_poll_use_fallback_answer_ordering"),
        ("predictions", "0005_poolstagerule_level_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activematchmessage",
            name="ticker_state",
            field=models.IntegerField(
                choices=[(0, "Unknown"), (1, "Starting soon"), (2, "In progress"), (3, "Result posted")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="activematchmessage",
            name="thread_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PoolNotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notify_missing_votes",
                    models.BooleanField(
                        default=True,
                        help_text="Ping this user before kickoff when they have not voted on a match in this pool.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="predictions.predictionpool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "pool")},
            },
        ),
    ]
