# Generated by Django 6.0.8 on 2026-08-30 14:50

from django.db import migrations, models


def dont_welcome_running_pools(apps, schema_editor):
    """Every binding that already exists is a pool already under way.

    The field defaults to True so a *new* binding is announced, which is the
    point of it - but applying that default to the pools running right now
    would ping their notification roles with a "welcome to the new season"
    post mid-season, on nothing more than a deploy.
    """
    apps.get_model("discord_bot", "DiscordGuildPool").objects.update(announce_welcome=False)


class Migration(migrations.Migration):

    dependencies = [
        ("discord_bot", "0005_activematchmessage_ticker_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordguildpool",
            name="announce_welcome",
            field=models.BooleanField(
                default=True,
                help_text="Post a welcome message in the channel introducing this pool. It goes out once, pings the notification role, and is then kept up to date by edits.",
            ),
        ),
        migrations.AddField(
            model_name="discordguildpool",
            name="welcome_msg",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(dont_welcome_running_pools, migrations.RunPython.noop),
    ]
