# Generated by Django 6.0.8 on 2026-08-30 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_bot", "0006_pool_onboarding_messages"),
        ("sports", "0003_add_nflverse_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessagePreviewRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kinds",
                    models.JSONField(
                        default=list,
                        help_text="PreviewMessageKind values to post, in the order the channel would see them.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for the bot"),
                            ("posted", "Posted"),
                            ("failed", "Failed"),
                            ("cleaned", "Removed again"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("posted_message_ids", models.JSONField(blank=True, default=list)),
                ("cleanup_requested", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("cleaned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "guild_pool",
                    models.ForeignKey(
                        help_text="Which pool binding to post into - that is the guild and the channel.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview_requests",
                        to="discord_bot.discordguildpool",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        help_text="The fixture to render. Any match of the season will do; nothing about it is changed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview_requests",
                        to="sports.match",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_preview_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
