# Generated by Django 6.0.8 on 2026-08-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_bot", "0007_messagepreviewrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordguildpool",
            name="welcome_is_v2",
            field=models.BooleanField(default=False),
        ),
    ]
